### PR TITLE
Re add semver

### PR DESCRIPTION
**Pull request by jungziege**

### CODE REVIEW

**Comment by bear** [comment]
IGYB

**Comment by kimh** [comment]
What's your goal here? In my opinion, maintaining semver right is difficult and shouldn't be used unless you have clear idea about what versioning means in your product. Doing otherwise just adds extra overhead of the maintenance.

**Comment by bear** [comment]
@kimh right now our goal is to get semver introduced in the places where it isn't so that we can have more options if we decide we do need it.

The images now are more likely to be shared across enterprise, .com and picard so having at least the common version pattern is going to help a lot going forward

**Comment by kimh** [comment]
So, I would propose we can introduce a new variable `ENTERPRISE_VERSION` in the Makefile and use it only in enterprise image. Here is why I propose this.

> The images now are more likely to be shared across enterprise, .com and picard so having at least the common version pattern is going to help a lot going forward

Although it's possible to share the image between different platforms, I think the direction we want to go is opposite: we want to be able to change independently to each platform's image. For example, we install many android SDK's in .com image but enterprise customers normally don't need android, so we don't install them. And when we need make a breaking change in Android SDK in .com and update major version, it doesn't make sense for enterprise images to have the major version update because they don't have Android SDK.

**Comment by jungziege** [comment]
Yeah, I realized semantic versioning is the right solution here anymore either. I want to adopt a different approach after watching Hickey's keynote last night. At least for enterprise, I'm going to keep it as the current versioning system, and then if we make and breaking changes, we will change the image name.

**Pull request closed without merging**
