### PR TITLE
Generating versions.json

### PR DESCRIPTION
**Pull request by kimh**
This is the first step for build-image doc automation. I also need know all installed versions inside container for the next image update.

### CODE REVIEW

**Comment by ndintenfass** [comment]
I'm wondering if this creates a new maintenance chore that risks creating out-of-date info. Is it not possible to tie generation of the Json more directly to the install of the packages, so the installer script itself emits what it's installing, preventing the need to maintain two separate lists of the same packages?

**Comment by kimh** [comment]
> preventing the need to maintain two separate lists of the same packages?

My plan is also maintaining a single `versions.json` generated on image-builder build and replacing https://github.com/circleci/circleci-docs/blob/master/jekyll/_data/trusty/versions.yml with it. In the end, we will just copy the file to circleci-docs repo and push to Github so that it's sync automatically.

> Is it not possible to tie generation of the Json more directly to the install of the packages, so the installer script itself emits what it's installing

This is possible. In that case, we can create a bash function that spits the version and every installation script calls the function. However, I'm not sure if this has fewer maintenance cost than the approach in this PR.

In both cases, there is a possibility of creating out-of-date info. In your suggested approach, one may miss calling the function when adding a new installation script. In my approach, one may miss updating `pkg-versions.sh` when adding a new software. But I think the implementation is a bit more complex in your approach.

Having said these, I think your biggest concern is maintaining two versions file in image-builder and circleci-docs but that's not the case.

**Comment by ndintenfass** [comment]
More maintaining both the list to check and the actual install. I was thinking circle-install could log what it's installing, with optional additional logging from the individual scripts.

**Comment by kimh** [comment]
> I was thinking circle-install could log what it's installing

Do you have specific data structure that you have in mind to keep track what's installed? JSON, yaml or something else? (it must be decent data structure so that we can feed into circleci-docs). The reason why I prefer to spitting all versions at once over spitting one version per installation is because it's not trivial to append data to existing data structure in bash.

Suppose you already have a json file like the following.

```
{"summary": {
    mysql: "1.1.1",
    postgresql: "1.1.1"
  }
}
```

Then inserting `redis: "2.2.2"` to the existing json is very trivial in bash (i.g. adding a comma to the last element).

I may misunderstand your intention. In that case, concrete example would help.

**Comment by ndintenfass** [comment]
My thinking was that when we want to add a new package we are touching more places than necessary -- looking to optimize around maintenance rather than around implementation. My original thought was that since we pass to `circle-install` the name of a package and a version we could log directly from in there (parsing a log into json would not be daunting), though it might make even more sense to have each script in /circleci-provision-scripts responsible for logging what it installs -- even moving each of the lines in your script to inside the provisioning script would mean one fewer place to update when adding a package.

**Comment by kimh** [comment]
Not all `circle-install` scripts support versions.

```
# This installs whatever the latest version of postgres via apt
circleci-install postgres 

# This installs PhantomJS from our S3 and version is hardcoded inside the script
circleci-install phantomjs
```

So, at this moment we can only log versions automatically for circleci-install that supports version. If we want to log all versions, we need to improve `circleci-install` scripts but my short team goal is knowing all versions installed in the build image so that I can create a diff for the next container image update for customers (sorry, I haven't told you about this goal).

How about addressing your proposal as a task of automatic doc update project?

**Comment by kimh** [comment]
@ndintenfass I want to ship a new build image soon in this week . To notify our customers, I need `pkg-versions.sh` script to dump what's installed in the build image. So, I'll merge this for now and let's resume our discussion.

**Pull request merged**
